-- Supporta più fasce orarie per giorno (es. mattina/pomeriggio con pausa)
-- rimuovendo la PK composita (fk_struttura, giorno_settimana) che ammetteva
-- una sola riga per giorno, e sostituendola con un id surrogato.

ALTER TABLE "public"."Orari_Strutture"
  DROP CONSTRAINT IF EXISTS "Orari_Centri_Sportivi_pkey";

ALTER TABLE "public"."Orari_Strutture"
  ADD COLUMN IF NOT EXISTS "id" bigint GENERATED BY DEFAULT AS IDENTITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Orari_Strutture_pkey'
  ) THEN
    ALTER TABLE "public"."Orari_Strutture"
      ADD CONSTRAINT "Orari_Strutture_pkey" PRIMARY KEY ("id");
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "idx_orari_strutture_fk_struttura"
  ON "public"."Orari_Strutture" ("fk_struttura", "giorno_settimana");
